from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"
STORAGE_FORMAT = "csv"
PRICE_DATA_DIR = DATA_DIR / "prices"
FACTOR_DATA_DIR = DATA_DIR / "factors"
FUNDAMENTAL_DATA_DIR = DATA_DIR / "fundamentals"
INDUSTRY_DATA_DIR = DATA_DIR / "industries"
STOCK_DATA_DIR = FACTOR_DATA_DIR
SELECTED_CANDIDATES_PATH = DATA_DIR / "selected_candidates.csv"
SIGNAL_DATA_DIR = DATA_DIR / "signals"
DAILY_SIGNAL_SCORES_PATH = SIGNAL_DATA_DIR / "daily_signal_scores.csv"
BENCHMARK_WEIGHT_DIR = DATA_DIR / "benchmark_weights"

LOOKBACK_DAYS = 120
MIN_REQUIRED_DAYS = 60
TRADING_DAYS_PER_YEAR = 252

# 股票池配置
UNIVERSE_INDEX = "沪深300"
UNIVERSE_INDEX_SYMBOL = "000300"
UNIVERSE_SOURCE = "csindex"  # csindex / eastmoney
UNIVERSE_SIZE_LIMIT = 100
BENCHMARK_SYMBOL = "000300"
BENCHMARK_WEIGHT_SOURCE = "akshare"
STRATEGY_TYPE = "equity_index_enhanced"
LONG_QUANTILE = 0.20
SHORT_QUANTILE = 0.20
INDUSTRY_WEIGHT_CAP = 0.20
VOLATILITY_TARGET_COLUMN = "volatility_20d"
FACTOR_WINSORIZE_LOWER = 0.01
FACTOR_WINSORIZE_UPPER = 0.99
BENCHMARK_ACTIVE_TILT = 0.50

# 选股配置
# 风控和仓位配置
MAX_POSITION_PER_STOCK = 0.10
MAX_TOTAL_POSITION = 0.60

# 过滤配置
FILTER_ST = True
FILTER_SUSPENDED = True

# Qlib backtest configuration
QLIB_ENABLED = True
QLIB_PROVIDER_URI = DATA_DIR / "qlib"
QLIB_BACKTEST_WINDOW = 60
QLIB_BENCHMARK = "SH000300"
QLIB_ACCOUNT = 1_000_000
QLIB_OPEN_COST = 0.0005
QLIB_CLOSE_COST = 0.0015
QLIB_MIN_COST = 5
QLIB_REPORT_DIR = DATA_DIR / "qlib_reports"
QLIB_BACKTEST_COMPARISON_PATH = QLIB_REPORT_DIR / "qlib_backtest_comparison.json"

# Qlib model research configuration
TRAINING_LOOKBACK_DAYS = 500
TRANSFORMER_RETRAIN_ON_DAILY_RUN = False
TRANSFORMER_INFERENCE_ENABLED = True
TRANSFORMER_MODEL_DIR = DATA_DIR / "model_reports"
TRANSFORMER_LABEL_HORIZON = 5
TRANSFORMER_LABEL_MODE = "cross_sectional_excess"
TRANSFORMER_FEATURE_NORMALIZATION = "cross_sectional_zscore"
TRANSFORMER_FEATURE_MISSING_MAX = 0.30
TRANSFORMER_FEATURE_MIN_STD = 1e-8
TRANSFORMER_FEATURE_MIN_ABS_RANKIC = 0.005
TRANSFORMER_FEATURE_WINSORIZE_LOWER = 0.01
TRANSFORMER_FEATURE_WINSORIZE_UPPER = 0.99
TRANSFORMER_MODEL_PATH = TRANSFORMER_MODEL_DIR / "transformer_model.pth"
TRANSFORMER_PREDICTION_PATH = TRANSFORMER_MODEL_DIR / "transformer_predictions.csv"
TRANSFORMER_LIVE_PREDICTION_DIR = TRANSFORMER_MODEL_DIR / "live_predictions"
TRANSFORMER_LIVE_MIN_SNAPSHOT_DAYS = 2
TRANSFORMER_WALK_FORWARD_ENABLED = True
TRANSFORMER_WALK_FORWARD_TRAIN_YEARS = 6
TRANSFORMER_WALK_FORWARD_VALID_YEARS = 1
TRANSFORMER_WALK_FORWARD_TEST_YEARS = 1
TRANSFORMER_WALK_FORWARD_START_YEAR = 2010
TRANSFORMER_WALK_FORWARD_END_YEAR = None
TRANSFORMER_WALK_FORWARD_MODEL_DIR = TRANSFORMER_MODEL_DIR / "walk_forward_models"
TRANSFORMER_WALK_FORWARD_PREDICTION_PATH = TRANSFORMER_MODEL_DIR / "transformer_walk_forward_predictions.csv"
TRANSFORMER_LIVE_TRAINING_ENABLED = True
TRANSFORMER_LIVE_TRAIN_YEARS = TRANSFORMER_WALK_FORWARD_TRAIN_YEARS
TRANSFORMER_LIVE_VALID_YEARS = TRANSFORMER_WALK_FORWARD_VALID_YEARS
TRANSFORMER_LIVE_MODEL_PATH = TRANSFORMER_MODEL_PATH
ALPHA_ANALYSIS_ENABLED = True
ALPHA_REPORT_DIR = DATA_DIR / "factor_reports"
ALPHA_SUMMARY_PATH = ALPHA_REPORT_DIR / "alpha_summary.json"
ALPHA_FACTOR_SELECTION_PATH = ALPHA_REPORT_DIR / "factor_selection.json"
ALPHA_SIGNAL_WEIGHTING_ENABLED = True
SIGNAL_CROSS_WEIGHTS = {
    "alpha": 0.70,
    "transformer": 0.20,
    "risk_liquidity": 0.10,
}
LIVE_ATTRIBUTION_ENABLED = True
GM_ATTRIBUTION_DIR = DATA_DIR / "gm_attribution"
LIVE_FACTOR_FEEDBACK_PATH = ALPHA_REPORT_DIR / "live_factor_feedback.json"
LIVE_PORTFOLIO_RULES_PATH = DATA_DIR / "portfolio_rules" / "live_portfolio_rules.json"

# TradingAgents LangGraph research configuration
TRADINGAGENTS_GRAPH_ENABLED = True
TRADINGAGENTS_SELECTED_ANALYSTS = ["market", "fundamentals", "news", "social"]
TRADINGAGENTS_RESEARCH_TOP_N = 5
TRADINGAGENTS_MAX_DEBATE_ROUNDS = 1
TRADINGAGENTS_MAX_RISK_ROUNDS = 1
TRADINGAGENTS_OUTPUT_LANGUAGE = "Chinese"
TRADINGAGENTS_RESULTS_DIR = DATA_DIR / "tradingagents_logs"
TRADINGAGENTS_CACHE_DIR = DATA_DIR / "tradingagents_cache"
AGENT_SIGNAL_DIR = DATA_DIR / "agent_signals"
AGENT_FEEDBACK_DIR = DATA_DIR / "agent_feedback"
AGENT_PERFORMANCE_FEEDBACK_PATH = AGENT_FEEDBACK_DIR / "agent_performance_feedback.json"

# EastMoney fallback/cache configuration
EASTMONEY_LIGHTWEIGHT_SPOT_ENABLED = True
EASTMONEY_REQUEST_TIMEOUT = 15
INDUSTRY_CACHE_ENABLED = True
INDUSTRY_REFRESH_DAYS = 30
INDUSTRY_FORCE_REFRESH = False

# 掘金量化执行配置
GM_EXECUTION_ENABLED = True
GM_ACCOUNT_ID = None  # 从环境变量 GM_ACCOUNT_ID 读取
