from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"
STORAGE_FORMAT = "csv"
PRICE_DATA_DIR = DATA_DIR / "prices"
FACTOR_DATA_DIR = DATA_DIR / "factors"
FUNDAMENTAL_DATA_DIR = DATA_DIR / "fundamentals"
INDUSTRY_DATA_DIR = DATA_DIR / "industries"
STOCK_DATA_DIR = FACTOR_DATA_DIR
SELECTED_CANDIDATES_PATH = DATA_DIR / "selected_candidates.csv"

LOOKBACK_DAYS = 120
MIN_REQUIRED_DAYS = 60
TRADING_DAYS_PER_YEAR = 252

# 股票池配置
UNIVERSE_INDEX = "沪深300"
UNIVERSE_INDEX_SYMBOL = "000300"
UNIVERSE_SOURCE = "csindex"  # csindex / eastmoney
UNIVERSE_SIZE_LIMIT = 100

# 选股配置
TOP_N = 10

# 风控和仓位配置
MAX_POSITION_PER_STOCK = 0.10
MAX_TOTAL_POSITION = 0.60

# 过滤配置
FILTER_ST = True
FILTER_SUSPENDED = True

# Qlib backtest configuration
QLIB_ENABLED = True
QLIB_PROVIDER_URI = DATA_DIR / "qlib"
QLIB_BACKTEST_WINDOW = 60
QLIB_BENCHMARK = "SH000300"
QLIB_ACCOUNT = 1_000_000
QLIB_OPEN_COST = 0.0005
QLIB_CLOSE_COST = 0.0015
QLIB_MIN_COST = 5

# Qlib model research configuration
TRAINING_LOOKBACK_DAYS = 500
TRANSFORMER_TRAINING_ENABLED = True
TRANSFORMER_MODEL_DIR = DATA_DIR / "model_reports"
TRANSFORMER_LABEL_HORIZON = 5
ALPHA_ANALYSIS_ENABLED = True
ALPHA_REPORT_DIR = DATA_DIR / "factor_reports"
ALPHA_SUMMARY_PATH = ALPHA_REPORT_DIR / "alpha_summary.json"
ALPHA_FACTOR_SELECTION_PATH = ALPHA_REPORT_DIR / "factor_selection.json"
ALPHA_SIGNAL_WEIGHTING_ENABLED = True
